app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
app_create:
    path:      /create
    defaults:  { _controller: AppBundle:Default:create}
    
warehouse:
    resource: '@WarehouseBundle/Controller/'
    type: annotation
